#!/bin/bash

# NOTE: The following code (finding the absolute pathname of this script)
# is from https://www.baeldung.com/linux/bash-get-location-within-script

SCRIPT_PATH="${BASH_SOURCE}"
while [ -L "${SCRIPT_PATH}" ]; do
  SCRIPT_DIR="$(cd -P "$(dirname "${SCRIPT_PATH}")" >/dev/null 2>&1 && pwd)"
  SCRIPT_PATH="$(readlink "${SCRIPT_PATH}")"
  [[ ${SCRIPT_PATH} != /* ]] && SCRIPT_PATH="${SCRIPT_DIR}/${SCRIPT_PATH}"
done
SCRIPT_PATH="$(readlink -f "${SCRIPT_PATH}")"
SCRIPT_DIR="$(cd -P "$(dirname -- "${SCRIPT_PATH}")" >/dev/null 2>&1 && pwd)"

# now add this directory to LUA_PATH so lua can find its scripts
env LUA_PATH="${SCRIPT_DIR}/?.lua;;" lua "${SCRIPT_DIR}/main.lua" "$@"
